services:
  web:
    build:
      context: .
      network: host
    network_mode: "host"
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env

networks: {} 
